# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Rochester Security Summit
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
#theme: minima
#plugins:
#  - jekyll-feed

collections:
  conferences:
    output: true
  keynotes:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "keynotes"
    values:
      layout: keynote
  -
    scope:
      path: ""
      type: "conferences"
    values:
      layout: conference

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# current conference year - used to show current information and to prevent
# current/upcoming conference from showing on past events page
current_year: 2023

# conference dates
conference_start_date: 2022-10-12
conference_end_date: 2022-10-13

# which year's sponsors should be shown on the homepage
# allows for previous year's to show up until the current year's list is final
homepage_sponsors_year: 2022
homepage_show_sponsors: true

# to show both the current and previous year's sponsors at the same time,
# set the following to true and specify a previous year 
homepage_show_previous_years_sponsors: true
homepage_previous_years_sponsors_year: 2022

# should the pre-conference "coming soon" message be shown on the homepage?
homepage_conference_announcement: false

# should the venue info be displayed on the homepage?
homepage_show_venue: true

# should the hotel info be displayed on the homepage?
homepage_show_hotels: false

# should keynote speakers be shown on homepage?
homepage_show_keynotes: true

homepage_show_app_links: true
homepage_show_post_conference_info: true




# should registration info be displayed on the homepage?
registraton_not_yet_open: true
registraton_enabled: false
registration_enabled_early_bird: false
registration_enabled_standard: false
registration_enabled_late: false
registration_sold_out: false
registration_event_concluded: false




sponsorship_not_yet_open: false
sponsorship_open: true
sponsorship_sold_out: false

# speaking messaging
speaking_cfp_not_yet_open: false
speaking_cfp_open: false
speaking_cfp_closed: false
speaking_show_guidelines: true
speaking_show_key_dates: true

# speaking key dates
speaking_proposals_due: 2022-08-01
speaking_committee_responses: 2022-08-15
speaking_materials_due: 2022-09-01
speaking_presentation_due: 2022-09-15

schedule_not_yet_available: true
schedule_tentative: false
schedule_available: false

